import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="bg-green-500 p-2 flex gap-5 px-2">
      <Link href="/" className="text-white font-bold">Home</Link>
      <Link href='dashboard' className="text-white font-bold"> Dashboard</Link>

      </nav>

      {children}
      </body>
      
    </html>
  );
}
